[package]
name = "strategy_runners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = "0.7.0"
trading_apis = {path = "../trading_apis" }
chrono = "0.4.19"
dotenv = "0.15.0"
