[package]
name = "strategy_optimizers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argmin = "0.6.0"
argmin-math = "0.1.0"
argmin_testfunctions = "0.1.1"
anyhow = "1.0.58"